### ISSUE TITLE
Version "0.8.1" won't compile on Windows 10 with MSYS2 using cargo build

### ISSUE THREAD

**Issue by mhavrlent** [alexcrichton/ssh2-rs#187] opened 2020-05-31 20:43 UTC
Version "0.8.1" won't compile on Windows 10 with MSYS2 (MinGW).
I tried also  "vendored" version. Same error.
My Cargo.toml for non-vendored version:
```
[dependencies]
ssh2 = "0.8.1"
```
vendored version:
```
[dependencies]
ssh2 = { version = "0.8.1", features = ["vendored-openssl"] }
```

**Versions:**
Windows: Microsoft Windows [Version 10.0.18363.836]
Rust: rustc 1.43.1 (8d69840ab 2020-05-04)
Toolchain: stable-x86_64-unknown-linux-gnu (default)
Toolchain cargo config: 
```
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
```
Output from MSYS2 pkg-config:
```
$ pkg-config --modversion openssl
1.1.1g
```
Installed openssl packages:
```
$ pacman -Ss openssl|grep -i installed
mingw32/mingw-w64-i686-openssl 1.1.1.g-1 [installed]
mingw64/mingw-w64-x86_64-openssl 1.1.1.g-1 [installed]
msys/libopenssl 1.1.1.g-1 (libraries) [installed]
msys/openssl 1.1.1.g-1 [installed]
msys/openssl-devel 1.1.1.g-1 (development) [installed]
$
```

**Error:**
`error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-L" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.10aeyyebyhjnvvn8.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.14jru11c26oe6kpq.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.226p2n118elvhl4b.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.2eq82xcjsbp46glv.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.2hguvj0bzcm3miyq.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.2j5m8fnrak2neilx.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.3cehdjigyvq6oo3z.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.3jozt05qmims78b3.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.4ckgkwhid5ipknzk.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.4ghq32q25gmj6yak.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.55oh91zf5vkbwbxx.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.ekszb4dztjtkar2.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.kv6x2u9e34i7i38.rcgu.o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.sk4vavzr43qfox4.rcgu.o" "-o" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.exe" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\rust_test1-2edcc81a0b60588c.2tb8uvxt1rdjkbfi.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps" "-L" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\build\\libssh2-sys-77e39414357d1647\\out\\build" "-L" "C:/msys64/mingw64/lib" "-L" "C:\\Users\\mipas\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-x86_64-pc-windows-gnu-0.4.0\\lib" "-L" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libslurp-c3c8934a377c5b63.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libssh2-4c022c08e5631909.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libparking_lot-64eddce2013c963d.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libparking_lot_core-e0b19cda1f821a4e.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libwinapi-3644d1f37b3d733c.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libsmallvec-ce915d4ae1fc9fcf.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libcfg_if-5bc5725eeb91809d.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\liblock_api-e4268f5db5cc955d.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libscopeguard-1e3937f3df9e247a.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libbitflags-a2e2f3dac167b3e2.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\liblibssh2_sys-ea580587a97545d3.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\liblibz_sys-f022e2267d618e5d.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\liblibc-2399a599f302d0c3.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libregex-713a6388a5b7a81d.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libthread_local-a042a30a7da1b604.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\liblazy_static-e4db2369f50ab5ed.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libregex_syntax-6ddd4c21943e2d32.rlib" 
"C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libaho_corasick-f081585d3f87e260.rlib" "C:\\Users\\mipas\\work\\git\\my\\rust_test1\\target\\debug\\deps\\libmemchr-2fb4314bdc6ecdf3.rlib" "-Wl,--start-group" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-b856675eeb99d410.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-7d9318240b1ba43e.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-1ea2d9c4ec771682.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-d40a2a1378721a73.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace-e7c77cc61316712f.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace_sys-160c2ebb98665c54.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-bd6bce6239a05021.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-c933f93cd63b2ad0.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-cabd342650cb5eba.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-14fea7a91cbd1d65.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-13f8aa678796468f.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-d5b2602ca33debca.rlib" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-d0a6bfc5adb4da72.rlib" "-Wl,--end-group" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-9bf35bb038f7db43.rlib" "-Wl,-Bdynamic" "-lwinapi_advapi32" "-lwinapi_cfgmgr32" "-lwinapi_kernel32" "-lwinapi_user32" "-lbcrypt" "-lcrypt32" "-luser32" "-lntdll" "-lz" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\mipas\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(channel.o): In function `_libssh2_channel_nextid':          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/channel.c:171: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):agent.c:(.data$_libssh2_wincng+0x0): first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(global.o):global.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(hostkey.o):hostkey.c:(.data$_libssh2_wincng+0x0): 
multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(keepalive.o): In function `libssh2_keepalive_config':
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/keepalive.c:81: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(kex.o):kex.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(knownhost.o):knownhost.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(mac.o):mac.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(misc.o): In function `_libssh2_error_flags':      
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/misc.c:375: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(packet.o):packet.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(scp.o):scp.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(session.o): In function `libssh2_session_banner_set':
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/session.c:1638: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(sftp.o):sftp.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(transport.o): In function `_libssh2_transport_read':
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/transport.c:505: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(userauth.o):userauth.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(wincng.o): In function `_libssh2_wincng_init':
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/wincng.c:918: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(bcrypt_pbkdf.o): In function `bcrypt_pbkdf':      
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/bcrypt_pbkdf.c:157: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(comp.o):comp.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(crypt.o):crypt.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(pem.o): In function `_libssh2_pem_parse':
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(crypt.o):crypt.c:(.data$_libssh2_wincng+0x0): multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(pem.o): In function `_libssh2_pem_parse':
          C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/pem.c:507: multiple definition of `_libssh2_wincng'
          C:\Users\mipas\work\git\my\rust_test1\target\debug\deps\liblibssh2_sys-ea580587a97545d3.rlib(agent.o):C:\Users\mipas\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.17/libssh2/src/agent.c:499: first defined here`

**Comment by 1480c1** [comment] 2020-06-07 20:14
https://github.com/libssh2/libssh2/commit/ba149e804ef653cc05ed9803dfc94519ce9328f7

seems to have been fixed 7 days ago in libssh2, and is not yet in libssh2-sys, which is then not in any of the packages that depend on libssh2-sys

**Comment by 1480c1** [comment] 2020-06-07 20:15
Annoyingly, I do not know how to fix this issue for my self since the package I am compiling pulls libssh2-sys 4 dependencies in.

**Comment by 1480c1** [comment] 2020-06-07 21:22
I found a way to fix it at least locally, in the project that uses `libssh2-sys` at some point, clone ssh2-rs, init submodule, move submodule remote to actual upstream URL, pull submodule, add 

```toml
[patch.crates-io]
libssh-sys = { path = "<path to libssh2-sys folder>" }
```
to the Cargo.toml
 and compile

**Comment by mati865** [comment] 2020-06-16 10:30
Tested and opened https://github.com/wez/libssh2/pull/2

**Comment by wez** [comment] 2020-06-29 16:04
I've updated the libssh2 dep to a more recent version of the windows fixes that we require.
This appears to build in the CI, but before I push updated packages to crates.io, I'd appreciate it if you could try pointing one of your real projects to github master and confirming that this resolves things.

**Comment by mati865** [comment] 2020-06-29 16:34
> This appears to build in the CI, but before I push updated packages to crates.io, I'd appreciate it if you could try pointing one of your real projects to github master and confirming that this resolves things.

Running `cargo test --no-run --target x86_64-pc-windows-gnu` was reproducing the issue. Windows-gnu is not tested on the CI.
Confirmed the issue is fixed by locally running testsuite for both i686 and x86_64 windows-gnu targets.

Thank you for fixing it!

**Comment by wez** [comment] 2020-06-29 16:52
OK, ssh2 0.8.2 and libssh2-sys 0.2.18 have been published!

**Closed by wez** 2020-06-29 16:52 UTC
