### ISSUE TITLE
How to change work directory

### ISSUE THREAD

**Issue by jiashiwen** [alexcrichton/ssh2-rs#234] opened 2021-11-09 02:27 UTC
hi:
i want to chang my work directory,the code is
```
    let mut channel = sess.channel_session().unwrap();
    channel.exec("ls /tmp").unwrap();
    let mut s = String::new();
    channel.read_to_string(&mut s).unwrap();
    println!("s is: {}", s);
    channel.wait_close();
    println!("{}", channel.exit_status().unwrap());
```
and the result is 
```
s is: systemd-private-8dc785bd4ed24cb58df55621db622f00-ntpd.service-3lFQUG

0
```
only one visible and when i use shell to execute `ls /tmp` the result is 
```
root@redis02:~/apache-maven-3.8.1# ls /tmp
hsperfdata_root
systemd-private-df7d065902c944a4a84676b0db889cfd-ntp.service-of4BAF
systemd-private-df7d065902c944a4a84676b0db889cfd-systemd-resolved.service-AVhkNs
tomcat.2554889109158061399.8080
```

and i use command `cd /root/apache-maven-3.8.1 && ls`
result is 
```
s is:
1
```

**Comment by yodaldevoid** [comment] 2021-12-28 18:24
What user are you connecting as? You might be running into permissions issues when trying to change your directory to `/root/apache-maven-3.8.1`.

Additionally, try running `cd /root/apache-maven-3.8.1 && ls` when logged into your shell to see the result. You may unintentionally be running different sets of commands between your two examples.

**Comment by sourcefrog** [comment] 2022-05-03 03:43
Your example doesn't include the code that actually tries to cd. But I suspect what you're seeing here is that every `exec` is launched as a separate process, so a cd by one isn't inherited by another.

You probably need to run a shell and pass multiple commands to a single shell exec, like `sh -c "cd /tmp && ls"`

**Comment by sourcefrog** [comment] 2023-01-08 05:55
I recommend to close this bug. It's not a bug in ssh2-rs, it's just a question about the unix process model and how SSH works in general, and it's now old.

**Closed** 2023-01-09 15:09 UTC
Labels: question
