### ISSUE TITLE
x86_64-pc-windows-msvc build fails

### ISSUE THREAD

**Issue by ierror** [alexcrichton/ssh2-rs#82] opened 2018-03-17 15:28 UTC
I'm trying to build on Windows 10, looks like problem with cmake. Any ideas how to solve?

- cmake version 3.11.0-rc3
- rustc 1.24.1 (d3ae9a9e0 2018-02-27)

```
error: failed to run custom build command for `libssh2-sys v0.2.6`
process didn't exit successfully: `Y:\ssh-permit-a38\target\release\build\libssh2-sys-e54262193525481a\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\boerni\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.6\\libssh2" "-G" "Visual Studio 15 2017 Win64" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=Y:\\ssh-permit-a38\\target\\x86_64-pc-windows-msvc\\release\\build\\libz-sys-e3d4347320821748\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=Y:\\ssh-permit-a38\\target\\x86_64-pc-windows-msvc\\release\\build\\libssh2-sys-34a0b1cb6fc34b56\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is MSVC 19.13.26128.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for include files windows.h, bcrypt.h
-- Looking for include files windows.h, bcrypt.h - not found
-- Configuring incomplete, errors occurred!
See also "Y:/ssh-permit-a38/target/x86_64-pc-windows-msvc/release/build/libssh2-sys-34a0b1cb6fc34b56/out/build/CMakeFiles/CMakeOutput.log".
See also "Y:/ssh-permit-a38/target/x86_64-pc-windows-msvc/release/build/libssh2-sys-34a0b1cb6fc34b56/out/build/CMakeFiles/CMakeError.log".

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at src/CMakeLists.txt:149 (elseif):
  given arguments:

    "REQUIRED" "STREQUAL"

  Unknown arguments specified


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\boerni\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.29\src\lib.rs:632:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by alexcrichton** [comment] 2018-03-17 17:47
Ah unfortunately I can't say I've ever seen that before :(

Maybe it's a cmake that's not new enough or something like that?

**Comment by Lisoph** [comment] 2018-06-18 13:57
Is cmake in your PATH?

**Comment by alexcrichton** [comment] 2018-08-14 17:41
Sorry I don't have a lot of time to dig into this right now, but a PR to help fix this would be much appreciated!

**Comment by foresterre** [comment] 2018-08-14 21:38
@alexcrichton If I find the problem and it is related to this repo, I will try create a fix and open a PR. Thanks for reacting!

@ErichDonGubler Thanks for thinking with me;
I had the same idea, except it also says `fatal: not a git repository (or any of the parent directories): .git`

It is indeed not a git repo:
I've also tried building from this directory (this is new for me, I'm guessing a bit, I've no idea whether it would work if the build were to be successful, or if the resulting build files need to be moved to another directory or not; anyhow, currently the build is still failing)

with `nightly-x86_64-pc-windows-gnu (default)`:
```
PS C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10> git status
fatal: not a git repository (or any of the parent directories): .git

PS C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10> cargo build
   Compiling libz-sys v1.0.20
error: failed to run custom build command for `libz-sys v1.0.20`
process didn't exit successfully: `C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10\target\debug\build\libz-sys-0e909acbe066b0c5\build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
cargo:rerun-if-changed=build.rs
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "make" "-f" "win32/Makefile.gcc" "install" "prefix=/C/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.10/target/debug/build/libz-sys-9d31ead5bcff14f3/out" "IMPLIB=" "INCLUDE_PATH=/C/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.10/target/debug/build/libz-sys-9d31ead5bcff14f3/out/include" "LIBRARY_PATH=/C/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.10/target/debug/build/libz-sys-9d31ead5bcff14f3/out/lib" "BINARY_PATH=/C/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.10/target/debug/build/libz-sys-9d31ead5bcff14f3/out/bin"
Error on line 100: expecting target : dependencies


command did not execute successfully, got: exit code: 1
```

```
PS C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10> fd Makefile.gcc
target\debug\build\libz-sys-276a2b7ab635ed60\out\build\win32\Makefile.gcc
target\debug\build\libz-sys-9d31ead5bcff14f3\out\build\win32\Makefile.gcc
```

The `Makefile.gcc` https://gist.github.com/foresterre/6a52ff6e0edee5cf0dce6112d6d58c8b
Which seems to belong to [libz-sys](https://github.com/alexcrichton/) instead of libssh2-sys (this repo)
It doesn't seem to help me though.

----------

with `nightly-x86_64-pc-windows-msvc`:
```
PS C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10> $env:RUST_BACKTRACE=1
PS C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10> cargo +nightly-x86_64-pc-windows-msvc build
   Compiling libssh2-sys v0.2.10 (file:///C:/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.10)
error: failed to run custom build command for `libssh2-sys v0.2.10 (file:///C:/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.10)`
process didn't exit successfully: `C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.10\target\debug\build\libssh2-sys-698f092beb289cf2\build-script-build` (exit code: 101)
--- stdout
running: "D:\\Tools\\CMake\\bin" "C:\\Users\\Marwen\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.10\\libssh2" "-G" "Visual Studio 15 2017 Win64" "-DCRYPTO_BACKEND=WinCNG" "-DENABLE_ZLIB_COMPRESSION=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\Marwen\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.10\\target\\debug\\build\\libssh2-sys-05ae97dff7bc7963\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_BUILD_TYPE=Debug"

--- stderr
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
failed to execute command: Access is denied. (os error 5)

build script failed, must exit now', C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.33\src\lib.rs:773:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:345
   9: cmake::fail
             at C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.33\src\lib.rs:773
  10: cmake::run
             at C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.33\src\lib.rs:751
  11: cmake::Config::build
             at C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.33\src\lib.rs:606
  12: build_script_build::main
             at .\build.rs:74
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  18: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  19: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: BaseThreadInitThunk
  25: RtlUserThreadStart

PS C:\Users\Marwen\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.33> cargo +nightly-x86_64-pc-windows-msvc build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling cc v1.0.18
   Compiling cmake v0.1.33 (file:///C:/Users/Marwen/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.33)
    Finished dev [unoptimized + debuginfo] target(s) in 9.17s

```

This is the same error, as my comment above. The shell is running as Administrator. I'm not sure which directory the `access is denied. (os error 5)` is for unfortunately. 

P.S. I thought the issue was the same as @ierror, but looking at the errors, it it similar but not equal (and the msvc and gnu versions seem different from each other too). Perhaps I should make a new a new issue?

**Comment by foresterre** [comment] 2018-08-20 18:36
After reinstalling Windows 10, and installing just the MSVC build tools and Rust with the latest nightly MSVC toolchain, the build succeeds. I've no clue where it did go wrong previously (to reproduce the failure consistently), therefore I can't try to create a patch. 

Thanks for looking with me though!

**Comment by steveklabnik** [comment] 2018-09-13 16:30
downgrading to 0.2.5 fixed it for me!

**Comment by foresterre** [comment] 2018-09-13 16:51
I noticed that it fails for me if I have the visual studio 2017 build tools in my `PATH` environment variable.

(like: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64`)

I'm not sure why though.

**Comment by alexcrichton** [comment] 2018-09-13 21:36
I've removed `cmake` in https://github.com/alexcrichton/ssh2-rs/pull/94, so this should be fixed now in theory

**Closed by alexcrichton** 2018-09-13 21:36 UTC
