### ISSUE TITLE
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1

### ISSUE THREAD

**Issue by insinfo** [alexcrichton/ssh2-rs#236] opened 2021-11-22 19:54 UTC
i'm trying to compile on windows and i'm getting this error,

```rs
fn main() {  
    println!("Hello, world! {}","sdf");
}
```

### Cargo.toml
```toml
[package]
name = "fsbackup_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9"
whoami = "1.1.1"
toml = "0.5.8"
rand = "0.8.4"
regex = "1.5.4"
lazy_static = "1.4.0"
log = "0.4.14"
bytesize = "1.1.0"
chrono = "0.4.19"
wildmatch = "2.0.0"
thiserror = "^1.0.0"

[target."cfg(target_family = \"unix\")"]
[target."cfg(target_family = \"unix\")".dependencies]
users = "0.11.0"

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.1.4"

```

```
cargo build
   Compiling libz-sys v1.1.3
   Compiling rand_chacha v0.3.1
   Compiling num-traits v0.2.14
   Compiling quote v1.0.10
   Compiling aho-corasick v0.7.18
   Compiling toml v0.5.8
   Compiling parking_lot_core v0.8.5
   Compiling time v0.1.44
   Compiling libssh2-sys v0.2.23
   Compiling syn v1.0.81
   Compiling rand v0.8.4
   Compiling num-integer v0.1.44
   Compiling regex v1.5.4
   Compiling parking_lot v0.11.2
   Compiling chrono v0.4.19
   Compiling thiserror-impl v1.0.30
   Compiling thiserror v1.0.30
   Compiling ssh2 v0.9.3
   Compiling fsbackup_engine v0.1.0 (C:\MyRustProjects\fsbackup_engine)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.1ui50u8fuayzqe56.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.1xmc7zjivlfp8nr8.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.223d2pvdkolzzaqw.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.22frl8ln2pls2y4p.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.29q70kd8jhiontt5.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.2b2kd6pyvgp93dly.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.35j07855z6n3sbqy.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3bhog7do8ojuvl79.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3hzsrkewdsdtt95l.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3tqf3lof41unxyro.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.bve6146ji1dzqnd.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3mxtcd1b58wzia2z.rcgu.o" "-L" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps" "-L" "C:\\rust\\cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-x86_64-pc-windows-gnu-0.4.0\\lib" "-L" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\build\\libssh2-sys-fc7c71d01a27467b\\out\\build" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:\\windows\\system32" "-L" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-c949a5d9f8ea17eb.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-4efbd26dc95f473b.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-11df657f271ec0b5.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-ed6e817a89285a21.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-a16c4de5bb48a9a6.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-b5d4a31ea91f9e86.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-01e22831e506e0c6.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-85865d75ad690c5e.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-91e2696c8ccb4461.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-186512436a4043bc.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-d0f4aee65f54d86f.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-42335e6cb2553e87.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-662baf24e2595e01.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-131219d6deabaad8.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-6530d4af942dc9d4.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-d1ec034e2d5fe483.rlib" "-Wl,--end-group" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-885492184211f20a.rlib" "-Wl,-Bdynamic" "-lkernel32" "-lws2_32" "-ladvapi32" "-luserenv" "-lkernel32" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.exe" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o: in function `pre_c_init':
          C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:134: undefined reference to `__p__fmode'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:135: undefined reference to `__p__commode'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o: in function `__tmainCRTStartup':
          C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:274: undefined reference to `_set_invalid_parameter_handler'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:283: undefined reference to `__p__acmdln'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-merr.o): in function `_matherr':
          C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/merr.c:46: undefined reference to `__acrt_iob_func'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o): in function `__report_error':
          C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/pseudo-reloc.c:149: undefined reference to `__acrt_iob_func'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/pseudo-reloc.c:150: undefined reference to `__acrt_iob_func'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `fsbackup_engine` due to previous error
PS C:\MyRustProjects\fsbackup_engine>
```

```
PS C:\MyRustProjects\fsbackup_engine> cc --version
cc.exe (Rev5, Built by MSYS2 project) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

![image](https://user-images.githubusercontent.com/12227024/142926059-759c19d8-e6c7-4b12-b8e7-d91f9026c14e.png)

**Comment by yodaldevoid** [comment] 2021-12-28 18:35
None of the missing symbols seem to be from `ssh2` or the underlying `libssh2`. I think you would encounter the same error when building without `ssh2-sys` and possibly without any other of the crates.

Because I don't think this is caused by `ssh2-rs` I am going to close this. If you can show that it is caused when adding `ssh2` to your project, please open this issue again.

**Closed by yodaldevoid** 2021-12-28 18:35 UTC

**Comment by insinfo** [comment] 2021-12-29 18:57
A rusty hello world app with no dependencies would compile normally. When I added the dependency "ssh2-rs" it generated this error. What solved the problem for me was installing mingw64 from chocolatey https://community.chocolatey.org/packages/mingw, commenting this here to help others who have this problem
