### ISSUE TITLE
Rebase libssh2 submodule?

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/ssh2-rs#191] opened 2020-06-29 14:56 UTC
I've noticed that builds locally for me are failing on MinGW, but it looks like the issue has been [fixed upstream](https://github.com/libssh2/libssh2/commit/ba149e804ef653cc05ed9803dfc94519ce9328f7). The submodule, however, is pointing to a fork and isn't pointing to upstream (presumably to include https://github.com/wez/libssh2/commit/55d75b2e99b0468129dce810303d2a47665c66ba), so could that patch be rebased on the current libssh2 to pull in the fixes?

**Comment by wez** [comment] 2020-06-29 15:43
I've pointed it to a version of https://github.com/libssh2/libssh2/pull/484 which looks like it might finally merge my DH fixes on Windows.
I don't trust git and submodules overly much, so I wouldn't be surprised if I have to make another pass to make the pinning stick properly!

**Comment by alexcrichton** [comment] 2020-06-29 15:49
Nice! That'd be perfect :)

**Comment by wez** [comment] 2020-06-29 16:53
ssh2 0.8.2 and libssh2-sys 0.2.18 have been published; confirmed resolved in https://github.com/alexcrichton/ssh2-rs/issues/187

**Closed by wez** 2020-06-29 16:53 UTC
