### ISSUE TITLE
MinGW debug build fails

### ISSUE THREAD

**Issue by willem66745** [alexcrichton/ssh2-rs#90] opened 2018-07-14 21:12 UTC
After the bump of libssh2-sys to 0.2.8 the MinGW build fails (only the debug build).

Workaround: enable LIBSSH2_SYS_USE_PKG_CONFIG flag in my local environment

Gist: https://gist.github.com/willem66745/c8584e3b91c42a08977767cdee8b73fb

**Comment by alexcrichton** [comment] 2018-07-16 00:50
Thanks for the report! Can you gist some details of what the problem is?

**Comment by willem66745** [comment] 2018-07-16 21:12
Gist included in the description.

**Comment by alexcrichton** [comment] 2018-07-17 04:52
Ah unfortunately that's due to having `gcc.exe` in the installation of the Rust compiler. If you remove the `rust-mingw` component of the Rust compiler, does it solve the issue for you? Another way to solve this is to download an MSVC toolchain and then use the MinGW target rather than using a MinGW toolchain

**Comment by willem66745** [comment] 2018-07-19 21:04
Regretfully I had limited time to experiment. Rustup didn't allow me to remove rust-mingw component. The alternative MSVC toolchain with gnu triplet give me linker troubles (still using link.exe, even when overruling that with .cargo/config).

Although I tried to overrule the cargo settings as described here as alternative: https://doc.rust-lang.org/cargo/reference/config.html with a custom linker and ar.

Regretfully the same result (output suggest it uses the mingw gcc version).

**Comment by alexcrichton** [comment] 2018-09-13 21:37
I've removed `cmake` in #94, so this should in theory be fixed now.

**Closed by alexcrichton** 2018-09-13 21:37 UTC

**Comment by sysesc** [comment] 2024-02-21 21:34
> After the bump of libssh2-sys to 0.2.8 the MinGW build fails (only the debug build).
> 
> Workaround: enable LIBSSH2_SYS_USE_PKG_CONFIG flag in my local environment
> 
> Gist: https://gist.github.com/willem66745/c8584e3b91c42a08977767cdee8b73fb

Hi,

thank you.
 
i was building on clangarm64 and ` LIBSSH2_SYS_USE_PKG_CONFIG=1` was what i needed.

In total i was using ` OPENSSL_NO_VENDOR=1 LIBSSH2_SYS_USE_PKG_CONFIG=1`.
