### ISSUE TITLE
Forward local port

### ISSUE THREAD

**Issue by JoyceBabu** [alexcrichton/ssh2-rs#218] opened 2021-05-13 15:45 UTC
How can I forward a local port to a remote port?

I understand that I can do a remote forward with `channel_forward_listen`. But I couldn't find an equivalent rust method for `ssh_channel_open_forward ` for direct port forwarding.

**Comment by mihirsamdarshi** [comment] 2021-09-17 16:58
+1 on this, I am looking for a similar method. @JoyceBabu did you find any solutions to this?

**Comment by yodaldevoid** [comment] 2021-09-19 23:30
Looking through `libssh2` itself, it doesn't look like there is an exact match for `libssh`'s `ssh_channel_open_forward`. I think `channel_forward_listen` (and the extended variant) is the closest that currently exists.

I'm going to close this issue for now as I don't think this a problem to be solved at the Rust level, but the underlying C library. Please ask on the [`libssh2` issue tracker](https://github.com/libssh2/libssh2/issues) or the [mailing list](https://lists.haxx.se/listinfo/libssh2-devel). If it turns out that I was missing a function, please let me know and I'll reopen this issue and we can work on adding any missing methods.

**Closed by yodaldevoid** 2021-09-19 23:30 UTC

**Comment by wez** [comment] 2021-09-20 01:33
FWIW, I think the idea is that you use https://docs.rs/ssh2/0.9.1/ssh2/struct.Session.html#method.channel_direct_tcpip to tell the ssh server to create a channel that connects to the target host.  Then your application uses read/write on the channel to send data to that remote host.

**Comment by mihirsamdarshi** [comment] 2021-09-20 01:41
@wez, thanks! Thats exactly what I did

I wrote this bit of code to implement local port forwarding using this library. I want to essentially create an analog of the ssh -L command (`ssh -NTf -L <local_port>:localhost:<remote_port> <remote_ip>`). The problem that I am running into is that if the request has a JSON body (or any other payload), it doesn't forward that body to the remote IP. Do you or anyone else have any pointers on learning more about how to handle this?

I have attached a gist with my code below.
https://gist.github.com/mihirsamdarshi/9035edf5b7279de8e11969e2527ec549

Thanks!

**Comment by JoyceBabu** [comment] 2021-09-20 08:13
@mihirsamdarshi I did not go ahead with the project.

**Comment by mihirsamdarshi** [comment] 2021-11-05 23:36
> To forward a local port, you need to first set up a local listener, accept loop, and each time you accept locally, you call `Session::channel_direct_tcpip` to create a new remote connection, and then your app needs to read/write the local socket and proxy the data into write/read calls on the remote channel.

Hey @wez, so I ended up writing the code you suggested (below), but I was running into a couple problems that maybe you could help me with. The below code reads and forwards the entire request from the host port to the remote port, but doesn't seem to read back the entire response from the remote port. I seem to consistently only get 17 bytes read from the response.

I suspect that this has something to do with the code being blocking, since I started off using the [`async-ssh2-rs-lite`](https://github.com/bk-rs/async-ssh2-lite) crate, which kind of works, but its not nearly as seamless as just using `ssh -L`.  There are delays when receiving complete responses that I can't seem to figure out how to start debugging.

I was looking through the `wezterm` source and noticed that you hadn't implemented port forwarding either, so maybe you're not the right person to ask, but I am new to Rust/TCP/libssh2, and any help pointing me where to start dealing with this problem would be really useful.

```rust
const BUFFER_SIZE: usize = 128

fn read_buf_bytes(
    full_req_len: &mut usize,
    full_req_buf: &mut Vec<u8>,
    reader_buf_len: usize,
    mut reader_buf: Vec<u8>,
) -> bool {
    // Added these lines for verification of reading requests correctly
    if reader_buf_len == 0 {
        // Added these lines for verification of reading requests correctly
        println!("No bytes read from response");
        false
    } else {
        *full_req_len += reader_buf_len;
        // we need not read more data in case we have read less data than buffer size
        if reader_buf_len < BUFFER_SIZE {
            // let us only append the data how much we have read rather than complete
            // existing buffer data as n is less than buffer size
            full_req_buf.append(&mut reader_buf[..reader_buf_len].to_vec()); // convert slice into vec
            false
        } else {
            // append complete buffer vec data into request_buffer vec as n == buffer_size
            full_req_buf.append(&mut reader_buf);
            true
        }
    }
}

/// Read the stream data and return stream data & its length.
fn read_stream<R: Read>(mut stream: R) -> (Vec<u8>, usize) {
    let mut request_buffer = vec![];
    // let us loop & try to read the whole request data
    let mut request_len = 0usize;
    loop {
        let mut buffer = vec![0; BUFFER_SIZE];
        // println!("Reading stream data");
        match stream.read(&mut buffer) {
            Ok(n) => {
                if !read_buf_bytes(&mut request_len, &mut request_buffer, n, buffer) {
                    break;
                }
            }
            Err(e) => {
                println!("Error in reading request data: {:?}", e);
                break;
            }
        }
    }

    (request_buffer, request_len)
}

/// Read the stream data and return stream data & its length.
fn read_channel<R: Read>(channel: &mut R) -> (Vec<u8>, usize) {
    let mut response_buffer = vec![];
    // let us loop & try to read the whole request data
    let mut response_len = 0usize;
    loop {
        let mut buffer = vec![0; BUFFER_SIZE];
        // println!("Reading stream data");
        let future_stream = channel.read(&mut buffer);
        thread::sleep(Duration::from_millis(10));

        match future_stream {
            Ok(n) => {
                if !read_buf_bytes(&mut response_len, &mut response_buffer, n, buffer) {
                    break;
                }
            }
            Err(e) => {
                println!("Error in reading response data: {:?}", e);
                break;
            }
        }
    }

    (response_buffer, response_len)
}

fn handle_req<R: Runtime>(session: Arc<Session>, mut stream: TcpStream, window: tauri::Window<R>) {
    if let Ok(channel) = session.channel_direct_tcpip("localhost", REMOTE_WEB_CLIENT_PORT, None) {
        let mut channel = Box::new(channel);
        // read the user-facing TCPStream
        let (request, req_bytes) = read_stream(&mut stream);

        println!(
            "REQUEST ({} BYTES): {}",
            req_bytes,
            String::from_utf8_lossy(&request[..])
        );
        // send the incoming request over the channel to the remote localhost and port
        match channel.write_all(&request[..req_bytes]) {
            Ok(_) => (),
            Err(e) => window
                .emit(
                    "backend_error",
                    format!("Failed to forward request, error: {}", e),
                )
                .unwrap(),
        };
        channel.flush().unwrap();

        // read the response from the channel to the remote server
        let (response, res_bytes) = read_channel(&mut channel);

        // then forward the response to the user-facing TCPStream
        match stream.write_all(&response[..res_bytes]) {
            Ok(_) => (),
            Err(e) => window
                .emit(
                    "backend_error",
                    format!("Failed to write response, error: {}", e),
                )
                .unwrap(),
        };
        stream.flush().unwrap();
        println!("SENT {} BYTES AS RESPONSE\n", res_bytes);
        channel.close().expect("Failed to close channel");
    } else {
        window
            .emit("backend_error", "Failed to open channel".to_string())
            .unwrap();
    };
}

/// Searches for open local ports in the given range. This function is necessary
/// because it may not always be possible to open a single static port on the
/// user's computer, for example if they are developing applications or running
/// Docker containers.
fn get_listener_in_port_range(port_range: Range<u16>) -> Result<TcpListener, String> {
    for port in port_range.clone() {
        if let Ok(listener) = TcpListener::bind(("127.0.0.1", port)) {
            return Ok(listener);
        } else {
            continue;
        };
    }
    Err(format!(
        "No ports in range {} - {} available",
        &port_range.start, &port_range.end
    ))
}

async fn listen_on_forwarded_port<R: Runtime>(
    ssh_session: Arc<Session>,
    sender: Sender<Result<SocketAddr, String>>,
    should_exit: Arc<AtomicBool>,
    window: tauri::Window<R>,
) -> std::io::Result<()> {
    match get_listener_in_port_range(1000..2000) {
        Ok(listener) => {
            // if the listener is successfully created, then we can start listening on the
            // port, then get the local address
            if let Ok(address) = listener.local_addr() {
                sender.send(Ok(address)).unwrap();
            } else {
                // send the local address to the main thread
                sender
                    .send(Err(
                        "Could not retrieve address from TCPListener".to_string()
                    ))
                    .unwrap();
            }

            // loop over incoming TCPStreams (requests)
            for stream in listener.incoming() {
                let cloned_session = Arc::clone(&ssh_session);
                let cloned_window = window.clone();
                // check that the shared AtomicBool does not say to exit the TCPStream
                if should_exit.load(Ordering::SeqCst) {
                    println!("Received close connection signal");
                    break;
                }

                match stream {
                    Ok(stream) => {
                        thread::spawn(move || handle_req(cloned_session, stream, cloned_window));
                    }
                    Err(e) => panic!("encountered error: {}", e),
                }
            }
        }
        Err(e) => sender.send(Err(e)).unwrap(),
    }

    println!("TCP Listener stopped");

    Ok(())
}
```

**Comment by tbarusseau** [comment] 2022-03-21 22:17
Is there any definitive answer as to how we're supposed to do this? Even with [`Channel::channel_direct_tcpip`][1], I have issues understanding what I could do with that next.

My use-case is to access a database that's only locally-accessible through SSH. So first you log-in via SSH, then you log in the local database.

It's fairly common and most database clients allow a SSH tunnel before authenticating (for security reasons), for example [Beekeeper Studio][2] but I'm sure a lot of them have this feature.

After a quick search I see that [`pigeon-rs`][3] simply does it by [spawning a `ssh` process.][4] I guess this will have to do for now 😄

[1]: https://docs.rs/ssh2/latest/ssh2/struct.Session.html#method.channel_direct_tcpip
[2]: https://www.beekeeperstudio.io/
[3]: https://github.com/quambene/pigeon-rs
[4]: https://github.com/quambene/pigeon-rs/blob/master/src/data_sources/ssh_tunnel.rs#L35

**Comment by devinMcArthur** [comment] 2023-04-14 01:35
@mihirsamdarshi Where you ever able to get this figured out. I've been struggling with the exact same problem in Tauri.

**Comment by mihirsamdarshi** [comment] 2023-04-18 05:43
@devinMcArthur not really fully, but take a look at [my testing repo](https://github.com/mihirsamdarshi/ssh-test) that I made with a bunch of libraries. I would appreciate any help/PRs, if you have any ideas.

**Comment by Jimi-Harrold** [comment] 2023-08-30 09:26
> @mihirsamdarshi Were you ever able to get this figured out. I've been struggling with the exact same problem in Tauri.

> @devinMcArthur not really fully, but take a look at [my testing repo](https://github.com/mihirsamdarshi/ssh-test) that I made with a bunch of libraries. I would appreciate any help/PRs, if you have any ideas.

I've had to solve a similar problem in my app, it may not be exactly what you need but hopefully you can adapt the main io::copy threads to your exact application. I haven't done any benchmarks, but performance seems similar to the standard "```sss -L```" command.

```rust
use std::{sync::Arc, net::TcpListener};
use std::io::{self};
use log::{ error, warn, debug};
use ssh2::Session;

pub fn create_tunnel(host_server:String,host_port:u16, remote_server:String,remote_port:u16,session:Arc<Session>) -> Result<(),String>{
    match TcpListener::bind((host_server.as_str(), host_port)) {
        Err(err) => return Err(err.to_string()),
        Ok(listener) => {
            debug!("Succesfully bound {}:{} on host machine",host_server.as_str(),host_port);
            match session.channel_direct_tcpip(remote_server.as_str(), remote_port, None) {
                Err(err) => return Err(err.to_string()),
                Ok(channel) => {
                    debug!("Succesfully bound {}:{} on remote machine",host_server.as_str(),host_port);                
                    session.set_timeout(10000);//increase if you're timing out a lot
                    session.set_blocking(false);//very important, otherwise reading from channel will block whil waiting for data that may not arrive
                    let mut stream_id=0;

                    tokio::task::spawn_blocking(move || {
                        'listener_loop: loop{
                            match listener.accept(){
                                Err(err) => {
                                    error!("failed to accept connection, reason {:?}",err);
                                    break 'listener_loop;
                                },
                                Ok((stream,socket)) => {
                                    debug!("New TCP stream from socket {:}",socket);

                                    let mut reader_stream=stream;
                                    let mut  writer_stream=reader_stream.try_clone().unwrap();

                                    let  mut writer_channel={channel.stream(stream_id)};//open two streams on the same channel, so we can read and write seperatly 
                                    let  mut reader_channel={channel.stream(stream_id)};
                                    stream_id+=1;//new TCP streams bound to new channel streams

                                    //pipe stream output into channel
                                    tokio::task::spawn_blocking(move ||{
                                        loop{ 
                                            match io::copy(&mut reader_stream, &mut writer_channel){
                                                Ok(_) => (),
                                                Err(err) => {
                                                    error!("Failed to write to channel, reason: {:?}",err);
                                                    break
                                                },
                                            } 
                                        }
                                    }); 

                                    //pipe channel output into stream
                                    tokio::task::spawn_blocking(move ||{
                                        loop{ 
                                            match io::copy(&mut reader_channel, &mut writer_stream){
                                                Ok(_) => (),
                                                Err(err) => {
                                                    error!("Failed to read from channel, reason: {:?}",err);
                                                    break
                                                },
                                            } 
                                        }
                                    });                   
                                },  
                            }
                        }
                        //not accepting any more connections
                        warn!("Tunnel on {:}:{:}  to {:}:{:} closed!",host_server.as_str(),host_port,remote_server.as_str(),remote_port)
                    });
                },
            }            
        }, 
    };
 
    Ok(())
}
```

**Comment by oleksiys** [comment] 2025-06-23 21:43
@Jimi-Harrold Thank you for you code snippet, it gave me good ideas how to implement it. Unfortunately `io::copy` didn't work. As I understand this was caused by SSH streams (both read and write) often throw `io::ErrorKind::WouldBlock`, which in case of SSH write part lead to data corruption, since io::copy could've written just a part of buffer before throwing this error, so the rest could be just lost.
I basically re-wrote `io::copy` with a custom copy function:
```
fn copy_streams<R: Read, W: Write>(reader: &mut R, writer: &mut W) -> anyhow::Result<usize> {
    let mut bytes_copied = 0;
    let mut buffer = [0; 8192];
    loop {
        let bytes_read = read_blocking(reader, &mut buffer)?;
        if bytes_read == 0 {
            // No more data to read
            break;
        }
        write_all_blocking(writer, &buffer[..bytes_read])?;
        bytes_copied += bytes_read;
    }
    Ok(bytes_copied)
}

fn read_blocking<R: Read>(reader: &mut R, buffer: &mut [u8]) -> anyhow::Result<usize> {
    loop {
        match reader.read(buffer) {
            Ok(bytes_read) => {
                return Ok(bytes_read);
            }
            Err(e) if e.kind() == io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(20));
                continue;
            }
            Err(e) => bail!("Error reading from stream: {}", e),
        };
    }
}

fn write_all_blocking<W: Write>(writer: &mut W, buffer: &[u8]) -> anyhow::Result<usize> {
    let mut total_written = 0;
    loop {
        match writer.write(&buffer[total_written..]) {
            Ok(0) => {
                std::thread::sleep(Duration::from_millis(20));
                continue;
            }
            Ok(bytes_written) => {
                total_written += bytes_written;
                if total_written == buffer.len() {
                    return Ok(total_written);
                }
            }
            Err(e) if e.kind() == io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(20));
                continue;
            }
            Err(e) => bail!("Error reading from stream: {}", e),
        };
    }
}
```

at it seemed to be pretty stable so far.
